### ISSUE TITLE
[Bug]: Gemini Function calling crashes when BQ table has no description field

### ISSUE THREAD

**Issue by pentium10** [GoogleCloudPlatform/generative-ai#423]
### File Name

gemini/function-calling/sql-talk-app /app.py

### What happened?

When runing the example the code simply crashes for tables where there is no description set in BigQuery.

Modify the example so it works out of the box even for situation when no description of the table is available in BigQuery. 

### Relevant log output

```shell
024-02-25 16:53:59.154 Uncaught app exception
Traceback (most recent call last):
  File "D:\wamp\www\cloudnext_streamlit\.venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\wamp\www\cloudnext_streamlit\sql-talk-app\app.py", line 185, in <module>
    str(api_response["description"]),
KeyError: 'description'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pentium10** [comment]
@koverholt Can you take a look?
