### ISSUE TITLE
[Bug]: grpc_asynio throwing unexpected error

### ISSUE THREAD

**Issue by chintan-ushur** [GoogleCloudPlatform/generative-ai#739]
### File Name

types/generation_types.py

### What happened?

While trying to utilize asyncio in transport, observing below bug:

Below is the sample code:

```
genai.configure(transport="grpc_asyncio", api_key=GEMINI_API_KEY)
async def main(prompt):
    model = genai.GenerativeModel(
        "gemini-1.5-flash"  # Correct transport configuration
    )
    response = await model.generate_content(prompt)
    return response  # Return the result

async def start_async_process():
    tasks = []
    for i in range(5):
        task = asyncio.create_task(main(prompt))
        tasks.append(task)
    results = await asyncio.gather(*tasks)
    for result in results:
        print(result)

if __name__ == "__main__":
    # genai.configure(api_key=GEMINI_API_KEY)
    st = time.time()
    asyncio.run(start_async_process())
    print(time.time() - st)

```

### Relevant log output

```shell
Traceback (most recent call last):
  File "somefile.py", line 79, in <module>
    asyncio.run(start_async_process())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "somefile.py", line 72, in start_async_process
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "somefile.py", line 64, in main
    response = await model.generate_content(prompt)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/google/generativeai/generative_models.py", line 266, in generate_content
    return generation_types.GenerateContentResponse.from_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/google/generativeai/types/generation_types.py", line 514, in from_response
    return cls(
           ^^^^
  File ".venv/lib/python3.11/site-packages/google/generativeai/types/generation_types.py", line 354, in __init__
    if result.prompt_feedback.block_reason:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'prompt_feedback'
sys:1: RuntimeWarning: coroutine '_wrap_unary_errors.<locals>.error_remapped_callable' was never awaited

Process finished with exit code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by holtskinner** [comment]
Please refile this issue in https://github.com/google-gemini/generative-ai-python
